name: Build

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
   build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        vm_release: [ 201901172323 ]
        vm_family: [ squeak ]
        tensorflow: [ 2.3.1 ]
    name: TF ${{ matrix.tensorflow}}+${{ matrix.vm_family }} ${{ matrix.vm_release }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install TensorFlow
        run: ./scripts/install-tensorflow.sh
        env:
          VERSION: ${{ matrix.tensorflow }}
      - name: Clone VM and Cuis Image
        run: ./scripts/install-cuis.sh
        env:
          VM_RELEASE: ${{ matrix.vm_release }}
          VM_FAMILY: ${{ matrix.vm_family }}
      - name: Install updates
        run: ./scripts/ci/install-updates.sh
      - name: Load Packages
        run: ./scripts/install-packages.sh
      - name: Run Tests
        run: ./scripts/ci/run-tests.sh
        timeout-minutes: 20